spring:
#  // test DB (DB 없을 때 주석 풀고 사용)
#  datasource:
#    url: jdbc:h2:mem:test;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/exit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: exit
    password: 1234

  application:
    name: mtvs-3rd-be

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT.SECRET}
